management:
  endpoint:
    quickfixjclient:
      enabled: true
    quickfixjserver:
      enabled: true
  endpoints:
    web:
      exposure:
        include: quickfixjclient,quickfixjserver

quickfixj:
  client:
    auto-startup: true
    jmx-enabled: true
    message-store-factory: memory
    log-factory: screen
    requester:
      request: true
      mdentry: 0,1
      instruments: "{ISIN1: \"4\", CUSIP1: \"1\"}"
    config: ${QUICKFIXJ_CLIENT_CONFIG_FILE:classpath:quickfixj-client.cfg}

  server:
    auto-startup: true
    jmx-enabled: true
    message-store-factory: memory
    log-factory: screen
    publisher:
      publish: true
      schedule:
        period: 1
        time-unit: seconds
    config: ${QUICKFIXJ_SERVER_CONFIG_FILE:classpath:quickfixj-server.cfg}